package application.model.game;

public enum Genre {
	ACCOUNTING, VIDEO_PRODUCTION, RACING, ONLINE_MULTI_PLAYER, LINUX, CASUAL, EDUCATION, STEAM_ACHIEVEMENTS,
	FULL_CONTROLLER_SUPPORT, SHARED_SPLIT_SCREEN, NUDITY, INCLUDES_LEVEL_EDITOR, SOFTWARE_TRAINING, ONLINE_CO_OP,
	VALVE_ANTI_CHEAT_ENABLED, WEB_PUBLISHING, GORE, FREE_TO_PLAY, UTILITIES, VR_SUPPORT, GAME_DEVELOPMENT,
	MASSIVELY_MULTIPLAYER, AUDIO_PRODUCTION, MULTI_PLAYER, DESIGN_ILLUSTRATION, LOCAL_CO_OP, STEAMVR_COLLECTIBLES,
	INDIE, SEXUAL_CONTENT, SINGLE_PLAYER, EARLY_ACCESS, PARTIAL_CONTROLLER_SUPPORT, MAC, PHOTO_EDITING,
	STEAM_TURN_NOTIFICATIONS, STATS, STRATEGY, RPG, VIOLENT, COMMENTARY_AVAILABLE, IN_APP_PURCHASES, SIMULATION, ACTION,
	STEAM_LEADERBOARDS, WINDOWS, ANIMATION_MODELING, HUNTERS, STEAM_WORKSHOP, STEAM_TRADING_CARDS, STEAM_CLOUD, SPORTS,
	MMO, DOCUMENTARY, TUTORIAL, CROSS_PLATFORM_MULTIPLAYER, LOCAL_MULTI_PLAYER, ADVENTURE, CAPTIONS_AVAILABLE,
	INCLUDES_SOURCE_SDK, MISSING_GENRE, CO_OP;

	@Override
	public String toString() {
		String name = name();
		return toTitleCase(name);
	}

	private static String toTitleCase(String input) {
		StringBuilder titleCase = new StringBuilder();
		boolean nextTitleCase = true;

		for (char c : input.toCharArray()) {
			if (Character.isSpaceChar(c)) {
				nextTitleCase = true;
			} else if (nextTitleCase) {
				c = Character.toTitleCase(c);
				nextTitleCase = false;
			}

			titleCase.append(c);
		}
		return titleCase.toString();
	}
}
